version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - app_data:/code
    networks:
      - app_network
    command: python app.py

networks:
  app_network:

volumes:
  app_data:

