version: '3.8'

services:
  php:
    build: .
    container_name: php-server
    volumes:
      - ./php/src:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    restart: always
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:

